#------------------------------------------------------------------------------
# FILE:         action.yaml
# CONTRIBUTOR:  Jeff Lill
# COPYRIGHT:    Copyright (c) 2005-2021 by neonFORGE LLC.  All rights reserved.
#
# The contents of this repository are for private use by neonFORGE, LLC. and may not be
# divulged or used for any purpose by other organizations or individuals without a
# formal written and signed agreement with neonFORGE, LLC.

#------------------------------------------------------------------------------
# Clears the runner state including the GITHUB_WORKSPACE directory.
#
# NOTE: You must run the [setup-node] action before this to ensure that
#       Node.js is configured on the runner.

name: docker-login
description: "Logs into Docker using credentials stored in 1Password."
inputs:
  server:
    description: "Identifies the target registry service (typically ghcr.io or docker.io)"
    required: true
  credentials:
    description: "Identifies the login credentials stored in 1Password (typically GITHUB_PAT)"
    required: true
runs:
  using: node12
  main: action.js
